# -*- coding: utf8 -*-

## group
MAX_GROUPS_PER_USER = 10
GROUP_CAPACITY = 5
MIN_OPTIMAL_SIZE = 3
MAX_OPTIMAL_SIZE = 7
NEW_GROUP_MARKER_SECONDS = 600 #[+]
GOAL_TEXT_LENGTH = 160

## wish
MAX_WISHES_PER_USER = 5
MAX_TAGS_PER_WISH = 5
MAX_WISH_SIMILARITY = 0.75
WISH_EXPIRATION_DAYS = 90

## match
PROCESS_FREQUENCY_MINUTES = 1
MIN_NUMBER_OF_ACTIVE_WISHES = 2
MIN_NUMBER_OF_EDGES = 3
MIN_EDGE_SCORE = 0.5
ALGORITHM_VERSION = "0.2.5"

## login
BAN_PERIOD_MINUTES = 360
MAX_LOGIN_ATTEMPTS = 5

## tag
SCORE_UPDATE_FREQUENCY_MINUTES = 5

## communication
NOTIFICATION_FREQUENCY_MINUTES = 1