# -*- coding: utf8 -*-

## group
MAX_GROUPS_PER_USER = 10
GROUP_CAPACITY = 5

## wish
MAX_WISHES_PER_USER = 5
MAX_TAGS_PER_WISH = 5
MAX_WISH_SIMILARITY = 0.75
WISH_EXPIRATION_DAYS = 90

## match
MIN_NUMBER_OF_EDGES = 3
MIN_EDGE_SCORE = 0.5

## login
BAN_PERIOD_MINUTES = 360
MAX_LOGIN_ATTEMPTS = 5
INVITATION_EXPIRATION_DAYS = 10
MAX_INVITATION_CAPACITY = 50